
title: Frank Trani's Blog
email: frani@ftrani.com
description: A personal blog about web development and technology.
baseurl: ""
url: "https://ftrani.com"
twitter_username:
github_username:

# Build settings
markdown: kramdown
kramdown:
   math_engine: mathjax
theme: minima
plugins:
  - jekyll-feed
