title: Frank Trani's Blog
email: frani@ftrani.com
description: A personal blog about web development and technology.
baseurl: ""
url: "https://ftrani.com"
twitter_username:
github_username:

# Build settings
markdown: kramdown
mathjax: true
kramdown:
  math_engine: mathjax
theme: minima
plugins:
  - jekyll-feed

  
collections:
  posts:
    output: true
  notes:
    output: true
    permalink: /notes/:title/

